# Generated by Django 3.2.3 on 2021-05-31 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photos',
            field=models.ImageField(default='default.jpeg', upload_to='img'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
