# Generated by Django 3.2.3 on 2021-05-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210531_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photos',
            field=models.ImageField(default='default.jpg', upload_to='img'),
        ),
    ]
